/* Generated by Yosys 0.46 (git sha1 e97731b9dda91fa5fa53ed87df7c34163ba59a41, clang++ 17.0.6 -fPIC -O3) */

module soc_top(clk, rst_n);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
endmodule
